<?php


class parseConfig {
	const PARSE_API_URL 	= PARSE_SETTINGS_API_URL;
	const PARSE_APP_ID 		= PARSE_SETTINGS_APP_ID;
	const PARSE_CLIENT_KEY 	= PARSE_SETTINGS_CLIENT_ID;
	const PARSE_JS_KEY 		= PARSE_SETTINGS_JS_KEY;
	const PARSE_WIN_KEY 	= PARSE_SETTINGS_WINDOWS_KEY;
	const PARSE_API_KEY 	= PARSE_SETTINGS_API_KEY;
	const PARSE_MASTER_KEY 	= PARSE_SETTINGS_MASTER_KEY;
}

?>
